spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  application:
    name: sbb2-3

  profiles:
    active: main

  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: main
  datasource:
    url : jdbc:mysql://localhost:3306/sbb
    username: root
    password: lldj123414
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url : jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop